name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  test:
    name: Test Python ${{ matrix.python-version }}
    strategy:
      matrix:
        python-version: ["3.12"]
    uses: ./.github/workflows/reusable-build.yml
    with:
      python-version: ${{ matrix.python-version }}